### ISSUE TITLE
`monzo_amount_to_dec` will crash with amount between 0 and -1

### ISSUE THREAD

**Issue by thomasgravina** [pawelad/monz#3]
https://github.com/pawelad/monz/blob/5da82bab07a4f553e2a61187e891b44b44a88fcb/monz/utils.py#L18

**Comment by pawelad** [comment]
Good catch, thanks!

Feel free to open a PR with a fix, otherwise I'll try to find the time to do it this weekend.

**Comment by pawelad** [comment]
I'm very sorry it took sooo much time, but for what it's worth, this should be fixed in (the just released) [v1.0.0](https://github.com/pawelad/monz/releases/tag/v1.0.0).
