### ISSUE TITLE
Looks like it also print declined transactions.

### ISSUE THREAD

**Issue by thomasgravina** [pawelad/monz#4]

**Comment by pawelad** [comment]
Thanks for the report and well, I guess it does : )

What do you think should be the expected/correct behaviour? Not show them by default and have a flag like `--all` that will show them?

**Comment by pawelad** [comment]
I think I'm leaning towards showing all by default but have a flag that only shows accepted transactions, maybe a filter for top ups as well.

**Comment by pawelad** [comment]
I don't feel super strongly about it, but I think declined transactions _should_ be visible by default (they're now dimmed, to better show the difference).
