### ISSUE TITLE
How to pass account ID to subcommands

### ISSUE THREAD

**Issue by ScrumpyJack** [pawelad/monz#8]
"If you have only one then it will become the default one, but if you have more then you have to pass its ID explicitly to other subcommands."

how?
thanks

**Comment by pawelad** [comment]
Hiya,

I'm not exactly sure what you're asking about - do you have multiple accounts under one Monzo email? The wording is kinda confusing but [these](https://monzo.com/docs/#accounts) are the accounts I'm referencing.

**Comment by ScrumpyJack** [comment]
yes, I have two of those accounts. A closed pre-paid and a new current account.

$shell#>monz accounts

Account #1, My Name
ID:          acc_0000$string
Created:     Sep 5, 2017 1:00 PM

Account #2, My Name
ID:          acc_0000$otherstring
Created:     Nov 21, 2017 1:00 PM

Usage: monz [OPTIONS] COMMAND [ARGS]....

Options is token
Command is balance
So what arg do you need?

$shell#>monz balance acc_$otherstring
Usage: monz balance [OPTIONS]
Error: Got unexpected extra argument (acc_0000$otherstring)

**Comment by pawelad** [comment]
OK, so if you do `monz balance --help` you can see what the account parameter is:

```
$ monz balance --help
Usage: monz balance [OPTIONS]

  Show Monzo account balance

Options:
  -a, --account-id TEXT  Monzo account ID.
  --help                 Show this message and exit.
```

So doing `$ monz balance -a 'acc_$otherstring'` _should_ work. I actually never _really_ tested it, as I never had more then one account, so please do let me know if it works as expected : )

**Comment by ScrumpyJack** [comment]
Cool. That worked. I think usage should be more visible.
